### PR TITLE
Add Code Samples Support and Refactor Design

### PR DESCRIPTION
**Pull request by kadiryazici**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
With this PR;
- We can add sample codes to demos.
- Demo design and colors refactored for it to look pretty.

### CODE REVIEW

**Comment by aykutkardas** [comment]
image

Targets should not be buttons. I click it and I think it's not working.

**Comment by kadiryazici** [comment]
@aykutkardas acutally they were just elements for wowerlay to follow :D Do you think it is confusing?

**Comment by aykutkardas** [comment]
> @aykutkardas acutally they were just elements for wowerlay to follow :D Do you think it is confusing?

This would be misleading if the items that Wowerlay will follow and the items that I will interact with are in the same view.

**Comment by kadiryazici** [comment]
> > @aykutkardas acutally they were just elements for wowerlay to follow :D Do you think it is confusing?
> 
> This would be misleading if the items that Wowerlay will follow and the items that I will interact with are in the same view.

@aykutkardas so they should have different design but not the trigger button if I get it correctly. I will update it's design soon.

**Comment by kadiryazici** [comment]
@aykutkardas now I changed some stylings and converted sample texts to lorem ipsum.

**Review by aykutkardas — APPROVED** [review]

**Review by alpercun — APPROVED** [review]

**Review by denizcdemirci — APPROVED** [review]

**Pull request merged**
